Repository goormthon-Univ/2024_BEOTKKOTTHON_TEAM_21_BE, pull requests merged in 2024-03, with the labels that each got.

#4 1:1 채팅방 기능 고도화 & WebConfig 충돌 해결
  .gitignore
  src/main/java/com/teamkrews/chat/config/WebConfig.java
  src/main/java/com/teamkrews/chat/controller/ChatController.java
  src/main/java/com/teamkrews/chat/controller/ChatRoomController.java
  src/main/java/com/teamkrews/chat/controller/MessageController.java
  src/main/java/com/teamkrews/chat/handler/WebSockTextHandler.java
  src/main/java/com/teamkrews/chat/model/ChatRoomUser.java
  src/main/java/com/teamkrews/chat/repository/ChatRoomRepository.java
  src/main/java/com/teamkrews/chat/repository/MessageRepository.java
  src/main/java/com/teamkrews/chat/service/ChatRoomService.java
  src/main/java/com/teamkrews/chat/service/MessageService.java
  src/main/java/com/teamkrews/global/WebConfig.java
  src/main/java/com/teamkrews/global/WebSockConfig.java
  src/main/resources/templates/index.html
Labels: bug, enhancement

#7 팀명 생성기 API
  .github/ISSUE_TEMPLATE/feature_request.md
  build.gradle
  src/main/java/com/teamkrews/global/OpenAIConfig.java
  src/main/java/com/teamkrews/openAI/controller/TeamNameGeneratorController.java
  src/main/java/com/teamkrews/openAI/service/TeamNameGeneratorService.java
Labels: enhancement

#13 fix: 팀명 생성 API request/response Swagger 적용
  src/main/java/com/teamkrews/openAI/controller/TeamNameGeneratorController.java
  src/main/java/com/teamkrews/openAI/model/request/SeedWords.java
  src/main/java/com/teamkrews/openAI/model/response/TeamNames.java
  src/main/java/com/teamkrews/openAI/service/TeamNameGeneratorService.java
Labels: documentation

#17 fix: 채팅방 생성 1:1 로직 수정 및 ChatRoom-Workspace-User DB 수정
  src/main/java/com/teamkrews/User/model/User.java
  src/main/java/com/teamkrews/User/repository/UserRepository.java
  src/main/java/com/teamkrews/User/service/UserService.java
  src/main/java/com/teamkrews/chat/controller/ChatRoomController.java
  src/main/java/com/teamkrews/chat/model/ChatRoom.java
  src/main/java/com/teamkrews/chat/model/ChatRoomUser.java
  src/main/java/com/teamkrews/chat/model/request/ChatRoomCreationRequest.java
  src/main/java/com/teamkrews/chat/model/response/ChatRoomResponse.java
  src/main/java/com/teamkrews/chat/service/ChatRoomService.java
  src/main/java/com/teamkrews/openAI/service/TeamNameGeneratorService.java
  src/main/java/com/teamkrews/userworkspace/model/UserWorkspace.java
  src/main/java/com/teamkrews/workspace/model/Workspace.java
  src/main/java/com/teamkrews/workspace/model/response/WorkspaceInfoResponse.java
  src/main/java/com/teamkrews/workspace/repository/WorkspaceRepository.java
Labels: enhancement, help wanted

#19 1:1 채팅방 생성 & 목록 조회 수정
  src/main/java/com/teamkrews/User/model/User.java
  src/main/java/com/teamkrews/chat/controller/ChatRoomController.java
  src/main/java/com/teamkrews/chat/controller/MessageController.java
  src/main/java/com/teamkrews/chat/model/ChatRoom.java
  src/main/java/com/teamkrews/chat/model/ChatRoomUser.java
  src/main/java/com/teamkrews/chat/model/Message.java
  src/main/java/com/teamkrews/chat/model/request/ChatRoomCreationRequest.java
  src/main/java/com/teamkrews/chat/model/response/ChatRoomResponse.java
  src/main/java/com/teamkrews/chat/repository/ChatRoomUserRepository.java
  src/main/java/com/teamkrews/chat/repository/MessageRepository.java
  src/main/java/com/teamkrews/chat/service/ChatRoomService.java
  src/main/java/com/teamkrews/chat/service/MessageService.java
  src/main/java/com/teamkrews/workspace/model/Workspace.java
  src/main/java/com/teamkrews/workspace/model/request/WorkspaceUUIDRequest.java
Labels: enhancement

#24 Swagger 적용
  src/main/java/com/teamkrews/TeamKrewsApplication.java
  src/main/java/com/teamkrews/chat/controller/ChatRoomController.java
  src/main/java/com/teamkrews/chat/controller/MessageController.java
  src/main/java/com/teamkrews/chat/model/Message.java
  src/main/java/com/teamkrews/chat/repository/MessageRepository.java
  src/main/java/com/teamkrews/chat/service/MessageService.java
  src/main/java/com/teamkrews/global/WebConfig.java
  src/main/java/com/teamkrews/openAI/controller/TeamNameGeneratorController.java
  src/main/java/com/teamkrews/openAI/model/response/SavedTeamNameResponse.java
Labels: documentation

#27 refactor: @AuthenticationPrincipal 추가
  src/main/java/com/teamkrews/chat/controller/ChatRoomController.java
  src/main/java/com/teamkrews/openAI/controller/TeamNameGeneratorController.java
Labels: enhancement

#29 feat: 내가 보낸/받은 채팅방 목록 조회 기능 추가
  src/main/java/com/teamkrews/chat/controller/ChatRoomController.java
  src/main/java/com/teamkrews/chat/repository/ChatRoomUserRepository.java
  src/main/java/com/teamkrews/chat/service/ChatRoomService.java
Labels: enhancement

#28 [Refactor] 채팅 + 메시지 로직 수정
  .gitignore
  src/main/java/com/teamkrews/User/service/UserService.java
  src/main/java/com/teamkrews/auth/controller/AuthorizationExtractor.java
  src/main/java/com/teamkrews/chat/controller/ChatRoomController.java
  src/main/java/com/teamkrews/chat/controller/MessageController.java
  src/main/java/com/teamkrews/chat/model/ChatRoomMessage.java
  src/main/java/com/teamkrews/chat/model/Message.java
  src/main/java/com/teamkrews/chat/repository/ChatRoomMessageRepository.java
  src/main/java/com/teamkrews/chat/repository/MessageRepository.java
  src/main/java/com/teamkrews/chat/service/ChatRoomService.java
  src/main/java/com/teamkrews/chat/service/MessageService.java
  src/main/java/com/teamkrews/global/WebSockConfig.java
  src/main/java/com/teamkrews/global/exception/ErrorCode.java
Labels: Refactor

#35 Transform
  build.gradle
  src/main/java/com/teamkrews/chat/controller/MessageController.java
  src/main/java/com/teamkrews/openAI/model/request/MessageTranslatorDTO.java
  src/main/java/com/teamkrews/openAI/service/MessageTranslatorService.java
  src/main/java/com/teamkrews/openAI/service/TeamNameGeneratorService.java
Labels: enhancement

#39 refactor: 웹소켓 메시지 전송 기능 수정
  src/main/java/com/teamkrews/chat/controller/MessageController.java
  src/main/java/com/teamkrews/chat/model/request/MessageDTO.java
  src/main/java/com/teamkrews/chat/model/response/MessageResponse.java
  src/main/java/com/teamkrews/chat/service/ChatRoomService.java
  src/main/java/com/teamkrews/chat/service/MessageService.java
  src/main/java/com/teamkrews/global/WebSockConfig.java
  src/main/java/com/teamkrews/openAI/service/MessageTranslatorService.java
Labels: Refactor

#43 fix: 내가 보낸/받은 채팅방 @RequestParam 항목 수정
  src/main/java/com/teamkrews/chat/controller/ChatRoomController.java
  src/main/java/com/teamkrews/chat/service/ChatRoomService.java
Labels: bug

#44 Refactor/response
  src/main/java/com/teamkrews/chat/controller/ChatRoomController.java
  src/main/java/com/teamkrews/chat/model/response/ChatRoomDetailResponse.java
  src/main/java/com/teamkrews/chat/model/response/ChatRoomListResponse.java
  src/main/java/com/teamkrews/chat/model/response/UserInfoResponse.java
  src/main/java/com/teamkrews/chat/repository/ChatRoomUserRepository.java
  src/main/java/com/teamkrews/chat/service/ChatRoomService.java
Labels: documentation, enhancement

#45 [FEAT] 투두리스트 MVP 기능
  src/main/java/com/teamkrews/global/exception/ErrorCode.java
  src/main/java/com/teamkrews/todo/controller/TodoController.java
  src/main/java/com/teamkrews/todo/model/Todo.java
  src/main/java/com/teamkrews/todo/model/TodoCompleteDto.java
  src/main/java/com/teamkrews/todo/model/TodoCreateDto.java
  src/main/java/com/teamkrews/todo/model/TodoSelectDto.java
  src/main/java/com/teamkrews/todo/model/request/TodoCreateRequest.java
  src/main/java/com/teamkrews/todo/model/response/TodoInfoResponse.java
  src/main/java/com/teamkrews/todo/model/response/TodoInfoResponses.java
  src/main/java/com/teamkrews/todo/repository/TodoRepository.java
  src/main/java/com/teamkrews/todo/service/TodoService.java
  src/main/java/com/teamkrews/workspace/controller/WorkspaceController.java
Labels: enhancement

#48 fix: 말투변환기 api 수정
  src/main/java/com/teamkrews/chat/controller/MessageController.java
  src/main/java/com/teamkrews/openAI/service/MessageTranslatorService.java
Labels: bug
